### ISSUE TITLE
 Contact us form textfield and dropdown

### ISSUE THREAD

**Issue by andresfm8** [Sheridan-GDSC/Sheridan-GDSC-Website#29]
Component: Contact us

- Lock size of textfield 
- Fix size of dropdown

**Comment by sbelbeck** [comment]
@andresfm8  when I updated the text inputs/dropdown/text area to use styled components I also locked the size of the textarea in the 'styled' branch.

Would you mind taking a look to see if the dropdown is correct sizing in there now - it was such a slight difference in width I'm having a hard time noticing.

**Comment by andresfm8** [comment]
Fixed dropdown sizing, the issue was the box model.
